### ISSUE TITLE
miou and Acc value

### ISSUE THREAD

**Issue by zhuhaonan** [ahirsharan/SegNet#1]
Thank you for your code.
I have a question. When I trained on my data set, the mIou value didn't change, the Acc value was 100 all the time.It doesn't matter what the K value is.
![image](https://user-images.githubusercontent.com/15608275/100113433-44978c80-2eab-11eb-86c0-472a84615063.png)

**Comment by ahirsharan** [comment]
Hey! FYI currently, the code is functioning but I am not able to achieve the paper's accuracy. So, right now it won't give great results. But the issue you are facing is new to me. Can you tell me the format of dataset you are using or share the link? The training should happen correctly. I will definitely take a look.

**Comment by zhuhaonan** [comment]
> Hey! FYI currently, the code is functioning but I am not able to achieve the paper's accuracy. So, right now it won't give great results. But the issue you are facing is new to me. Can you tell me the format of dataset you are using or share the link? The training should happen correctly. I will definitely take a look.

![image](https://user-images.githubusercontent.com/15608275/100115740-d6a09480-2ead-11eb-8585-5b6e5d5dd4bc.png)
![image](https://user-images.githubusercontent.com/15608275/100115798-ec15be80-2ead-11eb-9f9d-0696d0325e74.png)
Thank you for your reply.This is the path of some of my data.Maybe I put the data on the wrong path?The images folder contains color images and the masks folder contains Ground Truth.

**Comment by zhuhaonan** [comment]
> Hey! FYI currently, the code is functioning but I am not able to achieve the paper's accuracy. So, right now it won't give great results. But the issue you are facing is new to me. Can you tell me the format of dataset you are using or share the link? The training should happen correctly. I will definitely take a look.

Or maybe my data is in the wrong format?
![image](https://user-images.githubusercontent.com/15608275/100175543-940ca580-2f09-11eb-943e-8ccfe9674bd0.png)

**Comment by ahirsharan** [comment]
The path and folder organisation is correct. The format of your masks would only work for binary segmentaion task since there is no such processing of dataset inside the code. The code assumes different mask color for each class (which is generally the case). I have already done that pre-processing and you may use my dataset for greater K. 

**FSS1000Aug**: [Link](https://drive.google.com/file/d/1IlqBFWmvsKl0jTcHNSNwTt7dr69wvI4q/view?usp=sharing)
The code is definitely not perfect and is in development. So, you are welcome to contribute. Also, if you have any other doubts, do let me know.

**Comment by zhuhaonan** [comment]
The problem was solved.Thank you for your reply :)
